package bista.shiddarth.live_pl_goal_printer.model

class DataMap {
    companion object {

        val teamIdMap = mapOf(
            1 to "ARS",
            2 to "AVL",
            3 to "BOU",
            4 to "BRE",
            5 to "BHA",
            6 to "CHE",
            7 to "CRY",
            8 to "EVE",
            9 to "FUL",
            10 to "IPS",
            11 to "LEI",
            12 to "LIV",
            13 to "MCI",
            14 to "MUN",
            15 to "NEW",
            16 to "NFO",
            17 to "SOU",
            18 to "TOT",
            19 to "WHU",
            20 to "WOL"
        )

        val playerIdMap = mapOf(
            1 to "Fábio Ferreira Vieira",
            2 to "Gabriel Fernando de Jesus",
            3 to "Gabriel dos Santos Magalhães",
            4 to "Kai Havertz",
            5 to "Karl Hein",
            6 to "Jurriën Timber",
            7 to "Jorge Luiz Frello Filho",
            8 to "Jakub Kiwior",
            9 to "Gabriel Martinelli Silva",
            10 to "Reiss Nelson",
            11 to "Eddie Nketiah",
            12 to "Ethan Nwaneri",
            13 to "Martin Ødegaard",
            14 to "Aaron Ramsdale",
            15 to "David Raya Martin",
            16 to "Declan Rice",
            17 to "Bukayo Saka",
            18 to "William Saliba",
            20 to "Thomas Partey",
            21 to "Kieran Tierney",
            22 to "miyasu Takehiro",
            23 to "Leandro Trossard",
            24 to "Benjamin White",
            25 to "Oleksandr Zinchenko",
            578 to "Riccardo Calafiori",
            597 to "Myles Lewis-Skelly",
            26 to "Álex Moreno Lopera",
            27 to "Cameron Archer",
            28 to "Leon Bailey",
            29 to "Ross Barkley",
            30 to "Enzo Barrenechea",
            31 to "Emiliano Buendía Stati",
            32 to "Matty Cash",
            33 to "Leander Dendoncker",
            34 to "Moussa Diaby",
            35 to "Diego Carlos Santos Silva",
            36 to "Lucas Digne",
            37 to "Lewis Dobbin",
            38 to "Jhon Durán",
            39 to "Joe Gauci",
            40 to "Kortney Hause",
            41 to "Samuel Iling-Junior",
            42 to "Boubacar Kamara",
            43 to "Kaine Kesler-Hayden",
            44 to "Ezri Konsa Ngoyo",
            45 to "Ian Maatsen",
            46 to "Filip Marschall",
            47 to "Emiliano Martínez Romero",
            48 to "John McGinn",
            49 to "Tyrone Mings",
            50 to "Kosta Nedeljković",
            51 to "Robin Olsen",
            52 to "Pau torres",
            53 to "Jacob Ramsey",
            54 to "Morgan Rogers",
            55 to "Viljami Sinisalo",
            56 to "Lino da Cruz Sousa",
            57 to "Youri Tielemans",
            58 to "Ollie Watkins",
            233 to "Amadou Onana",
            569 to "Jaden Philogene",
            598 to "Lamare Bogarde",
            59 to "Max Aarons",
            60 to "Tyler Adams",
            61 to "Jaidon Anthony",
            62 to "David Brooks",
            63 to "Ryan Christie",
            64 to "Lewis Cook",
            65 to "Enes Ünal",
            66 to "Romain Faivre",
            67 to "Hamed Traorè",
            68 to "James Hill",
            69 to "Daniel Jebbison",
            70 to "Milos Kerkez",
            71 to "Justin Kluivert",
            72 to "Chris Mepham",
            73 to "Norberto Murara Neto",
            74 to "Dango Ouattara",
            75 to "Alex Paulsen",
            76 to "Philip Billing",
            77 to "Alex Scott",
            78 to "Antoine Semenyo",
            79 to "Marcos Senesi",
            80 to "Luis Sinisterra",
            81 to "Adam Smith",
            83 to "Marcus Tavernier",
            84 to "Mark Travers",
            85 to "Illia Zabarnyi",
            580 to "Dean Huijsen",
            592 to "Julián Araujo Zúñiga",
            599 to "Will Dennis",
            86 to "Kristoffer Ajer",
            87 to "Ethan Brierley",
            88 to "Nathan Collins",
            89 to "Mikkel Damsgaard",
            90 to "Josh Dasilva",
            91 to "Mark Flekken",
            92 to "Rico Henry",
            93 to "Aaron Hickey",
            94 to "Vitaly Janelt",
            95 to "Mathias Jensen",
            96 to "Kim Ji-soo",
            97 to "Yunus Emre Konak",
            98 to "Keane Lewis-Potter",
            99 to "Bryan Mbeumo",
            100 to "Ben Mee",
            101 to "Christian Nørgaard",
            102 to "Frank Onyeka",
            103 to "Myles Peart-Harris",
            104 to "Ethan Pinnock",
            105 to "Mads Roerslev Rasmussen",
            106 to "Kevin Schade",
            107 to "Igor Thiago Nascimento Rodrigues",
            108 to "Ivan toney",
            109 to "Hákon Valdimarsson",
            110 to "Yoane Wissa",
            111 to "Yehor Yarmoliuk",
            112 to "Mathias Jorgensen",
            314 to "Fábio Freitas Gouveia Carvalho",
            602 to "Ryan Trevitt",
            113 to "Simon Adingra",
            114 to "Benicio Baker-Boaitey",
            115 to "Carlos Baleba",
            116 to "Valentín Barco",
            118 to "Amario Cozier-Duberry",
            119 to "Mahmoud Dahoud",
            120 to "Lewis Dunk",
            121 to "Julio Enciso",
            122 to "Pervis Estupiñán",
            123 to "Evan Ferguson",
            124 to "Billy Gilmour",
            125 to "Pascal Groß",
            126 to "Jack Hinshelwood",
            127 to "Ibrahim Osman",
            128 to "Igor Julio dos Santos de Paulo",
            129 to "João Pedro Junqueira de Jesus",
            130 to "Kacper Kozłowski",
            131 to "Tariq Lamptey",
            132 to "Solly March",
            133 to "Adrian Mazilu",
            134 to "James Milner",
            135 to "Yankuba Minteh",
            136 to "Mitoma Kaoru",
            137 to "Jakub Moder",
            138 to "Mark O’Mahony",
            139 to "Odeluga Offiah",
            140 to "Cameron Peupion",
            141 to "Jeremy Sarmiento Morante",
            142 to "Jason Steele",
            143 to "Deniz Undav",
            144 to "Jan Paul van Hecke",
            145 to "Joël Veltman",
            146 to "Bart Verbruggen",
            147 to "Adam Webster",
            148 to "Danny Welbeck",
            149 to "Mats Wieffer",
            595 to "Brajan Gruda",
            600 to "Yasin Ayari",
            601 to "Andrew Moran",
            150 to "Andrey Nascimento dos Santos",
            151 to "Ângelo Gabriel Borges Damaceno",
            152 to "Kepa Arrizabalaga",
            153 to "Benoît Badiashile",
            154 to "Lucas Bergström",
            155 to "Marcus Bettinelli",
            156 to "Armando Broja",
            157 to "Moisés Caicedo Corozo",
            158 to "Cesare Casadei",
            159 to "Trevoh Chalobah",
            160 to "Ben Chilwell",
            161 to "Carney Chukwuemeka",
            162 to "Levi Colwill",
            163 to "Marc Cucurella Saseta",
            164 to "David Datro Fofana",
            165 to "Deivid Washington de Souza Eugênio",
            166 to "Kiernan Dewsbury-Hall",
            167 to "Axel Disasi",
            168 to "Enzo Fernández",
            169 to "Conor Gallagher",
            170 to "Alfie Gilchrist",
            171 to "Malo Gusto",
            172 to "Reece James",
            173 to "Omari Kellyman",
            174 to "Roméo Lavia",
            175 to "Romelu Lukaku Bolingoli",
            176 to "Malang Sarr",
            177 to "Noni Madueke",
            178 to "Marc Guiu Paz",
            179 to "Mykhailo Mudryk",
            180 to "Nicolas Jackson",
            181 to "Christopher Nkunku",
            182 to "Cole Palmer",
            183 to "Đorđe Petrović",
            184 to "Renato Palma Veiga",
            185 to "Robert Sánchez",
            186 to "Raheem Sterling",
            187 to "Tosin Adarabioyo",
            188 to "Lesley Ugochukwu",
            189 to "Wesley Fofana",
            560 to "Pedro Lomba Neto",
            575 to "Caleb Wiley",
            581 to "Filip Jørgensen",
            190 to "Naouirou Ahamada",
            191 to "Joachim Andersen",
            192 to "Jordan Ayew",
            193 to "Cheick Doucouré",
            194 to "Chris Richards",
            195 to "Chadi Riad Dnanou",
            196 to "Nathaniel Clyne",
            197 to "Malcolm Ebiowei",
            198 to "Odsonne Edouard",
            199 to "Eberechi Eze",
            200 to "Marc Guéhi",
            201 to "Dean Henderson",
            202 to "Rob Holding",
            203 to "Will Hughes",
            204 to "Sam Johnstone",
            205 to "Daichi Kamada",
            206 to "Jefferson Lerma Solís",
            207 to "Jean-Philippe Mateta",
            208 to "Matheus França de Oliveira",
            209 to "Remi Matthews",
            210 to "Tyrick Mitchell",
            211 to "Daniel Muñoz",
            212 to "David Ozoh",
            213 to "Jesurun Rak-Sakyi",
            214 to "Jeffrey Schlupp",
            215 to "Joel Ward",
            216 to "Adam Wharton",
            585 to "Ismaïla Sarr",
            217 to "Abdoulaye Doucouré",
            218 to "Norberto Bercique Gomes Betuncal",
            219 to "Jarrad Branthwaite",
            220 to "Dominic Calvert-Lewin",
            221 to "Séamus Coleman",
            222 to "Idrissa Gueye",
            223 to "James Garner",
            224 to "Jack Harrison",
            225 to "Mason Holgate",
            226 to "Tim Iroegbunam",
            227 to "João Neves Virgínia",
            228 to "Michael Keane",
            229 to "Neal Maupay",
            230 to "Dwight McNeil",
            231 to "Vitalii Mykolenko",
            232 to "Iliman Ndiaye",
            234 to "Nathan Patterson",
            235 to "Jordan Pickford",
            236 to "James Tarkowski",
            237 to "Youssef Ramalho Chermiti",
            238 to "Ashley Young",
            577 to "Jesper Lindstrøm",
            582 to "Jake O'Brien",
            603 to "Harrison Armstrong",
            19 to "Emile Smith Rowe",
            239 to "Adama Traoré",
            240 to "Andreas Hoelgebaum Pereira",
            241 to "Calvin Bassey",
            242 to "Steven Benda",
            243 to "Tom Cairney",
            244 to "Timothy Castagne",
            245 to "Issa Diop",
            246 to "Luke Harris",
            247 to "Alex Iwobi",
            248 to "Bernd Leno",
            249 to "Saša Lukić",
            250 to "Kevin Mbabu",
            251 to "Rodrigo Muniz Carvalho",
            252 to "Raúl Jiménez",
            253 to "Tim Ream",
            254 to "Harrison Reed",
            255 to "Antonee Robinson",
            256 to "Jay Stansfield",
            257 to "Kenny Tete",
            258 to "Carlos Vinícius Alves Morais",
            259 to "Harry Wilson",
            579 to "Ryan Sessegnon",
            586 to "Jorge Cuenca Barreno",
            604 to "Josh King",
            605 to "Martial Godo",
            260 to "Ali Al-Hamadi",
            261 to "Elkan Baggott",
            262 to "Nathan Broadhead",
            263 to "Cameron Burgess",
            264 to "Wes Burns",
            265 to "Conor Chaplin",
            266 to "Harry Clarke",
            267 to "Leif Davis",
            268 to "Liam Delap",
            269 to "George Edmundson",
            270 to "Jacob Greaves",
            271 to "Marcus Myers-Harness",
            272 to "George Hirst",
            273 to "Cameron Humphreys",
            274 to "Omari Giraud-Hutchinson",
            275 to "Ben Johnson",
            276 to "Freddie Ladapo",
            277 to "Massimo Luongo",
            278 to "Sam Morsy",
            279 to "Corrie Ndaba",
            280 to "Cieran Slicker",
            281 to "Jack Taylor",
            282 to "Axel Tuanzebe",
            283 to "Christian Walton",
            284 to "Luke Woolfenden",
            359 to "Kalvin Phillips",
            568 to "Arijanet Muric",
            583 to "Conor townsend",
            611 to "Sam Szmodics",
            117 to "Facundo Buonanotte",
            285 to "Boubakary Soumaré",
            286 to "tom Cannon",
            287 to "Hamza Choudhury",
            288 to "Conor Coady",
            289 to "Patson Daka",
            290 to "Bobby De Cordova-Reid",
            291 to "Wout Faes",
            292 to "Michael Golding",
            293 to "Mads Hermansen",
            294 to "Daniel Iversen",
            295 to "James Justin",
            296 to "Victor Kristiansen",
            297 to "Wanya Marçal-Madivádua",
            298 to "Stephy Mavididi",
            299 to "Kasey McAteer",
            300 to "Wilfred Ndidi",
            301 to "Caleb Okoli",
            302 to "Ricardo Barbosa Pereira",
            303 to "Harry Souttar",
            304 to "Jakub Stolarczyk",
            305 to "Luke Thomas",
            306 to "Jamie Vardy",
            307 to "Jannik Vestergaard",
            308 to "Danny Ward",
            309 to "Harry Winks",
            570 to "Abdul Fatawu",
            606 to "Will Alves",
            310 to "Alisson Ramses Becker",
            311 to "Trent Alexander-Arnold",
            312 to "Stefan Bajčetić",
            313 to "Conor Bradley",
            315 to "Bobby Clark",
            316 to "Darwin Núñez",
            317 to "Diogo Jota",
            318 to "Ben Doak",
            319 to "Harvey Elliott",
            320 to "Endo Wataru",
            321 to "Cody Gakpo",
            322 to "Joe Gomez",
            323 to "Ryan Gravenberch",
            324 to "Curtis Jones",
            325 to "Caoimhin Kelleher",
            326 to "Ibrahima Konaté",
            327 to "Luis Díaz",
            328 to "Mohamed Salah",
            329 to "Alexis Mac Allister",
            330 to "James McConnell",
            331 to "Tyler Morton",
            332 to "Nathaniel Phillips",
            333 to "Jarell Quansah",
            334 to "Rhys Williams",
            335 to "Andrew Robertson",
            336 to "Dominik Szoboszlai",
            337 to "Konstantinos Tsimikas",
            338 to "Sepp van den Berg",
            339 to "Virgil van Dijk",
            340 to "Manuel Akanji",
            341 to "Nathan Aké",
            342 to "Bernardo Veiga de Carvalho e Silva",
            343 to "Oscar Bobb",
            344 to "Scott Carson",
            345 to "Kevin De Bruyne",
            346 to "Jérémy Doku",
            347 to "Ederson Santana de Moraes",
            348 to "Phil Foden",
            349 to "Jack Grealish",
            350 to "Joško Gvardiol",
            351 to "Erling Haaland",
            352 to "Julián Álvarez",
            353 to "João Cavaco Cancelo",
            354 to "Mateo Kovačić",
            355 to "Rico Lewis",
            356 to "Matheus Luiz Nunes",
            357 to "James McAtee",
            358 to "Stefan Ortega Moreno",
            360 to "Rodrigo 'Rodri' Hernandez",
            361 to "Rúben Gato Alves Dias",
            362 to "John Stones",
            363 to "Kyle Walker",
            571 to "Sávio 'Savinho' Moreira de Oliveira",
            607 to "Nico O'Reilly",
            364 to "Amad Diallo",
            365 to "Antony Matheus dos Santos",
            366 to "Bruno Borges Fernandes",
            367 to "Altay Bayindir",
            368 to "Carlos Henrique Casimiro",
            369 to "Diogo Dalot Teixeira",
            370 to "Christian Eriksen",
            371 to "Jonny Evans",
            372 to "Alejandro Garnacho",
            373 to "Hannibal Mejbri",
            374 to "Tom Heaton",
            375 to "Rasmus Højlund",
            376 to "Victor Lindelöf",
            377 to "Harry Maguire",
            378 to "Kobbie Mainoo",
            379 to "Tyrell Malacia",
            380 to "Lisandro Martínez",
            381 to "Scott Mctominay",
            382 to "Mason Mount",
            383 to "André Onana",
            384 to "Facundo Pellistri Rebollo",
            385 to "Marcus Rashford",
            386 to "Jadon Sancho",
            387 to "Luke Shaw",
            389 to "Joshua Zirkzee",
            572 to "Leny Yoro",
            593 to "Matthijs de Ligt",
            594 to "Noussair Mazraoui",
            613 to "toby Collyer",
            390 to "Alex Murphy",
            391 to "Miguel Almirón Rejala",
            392 to "Harvey Barnes",
            393 to "Sven Botman",
            394 to "Bruno Guimarães",
            395 to "Dan Burn",
            396 to "Martin Dúbravka",
            397 to "Ryan Fraser",
            398 to "Anthony Gordon",
            399 to "Lewis Hall",
            400 to "Isaac Hayden",
            401 to "Alexander Isak",
            402 to "Jacob Murphy",
            403 to "Joelinton Cássio Apolinário de Lira",
            404 to "Lloyd Kelly",
            405 to "Emil Krafth",
            406 to "Garang Kuol",
            407 to "Jamaal Lascelles",
            408 to "Jamal Lewis",
            409 to "Tino Livramento",
            410 to "Sean Longstaff",
            411 to "Lewis Miley",
            412 to "Odysseas Vlachodimos",
            413 to "Nick Pope",
            414 to "John Ruddy",
            415 to "Fabian Schär",
            416 to "Matt Targett",
            417 to "Sandro Tonali",
            418 to "Kieran Trippier",
            419 to "Joe White",
            420 to "Joe Willock",
            421 to "Callum Wilson",
            574 to "Miodrag Pivaš",
            590 to "William Osula",
            422 to "Ola Aina",
            423 to "Elliot Anderson",
            424 to "Taiwo Awoniyi",
            425 to "Willy Boly",
            426 to "Josh Bowler",
            427 to "Carlos Miguel dos Santos Pereira",
            428 to "Eric da Silva Moreira",
            429 to "Danilo dos Santos de Oliveira",
            430 to "Emmanuel Dennis",
            431 to "Nicolás Domínguez",
            432 to "Anthony Elanga",
            433 to "Morgan Gibbs-White",
            434 to "Callum Hudson-Odoi",
            435 to "Alex Mighten",
            436 to "Murillo Santiago Costa dos Santos",
            437 to "Neco Williams",
            438 to "Omar Richards",
            439 to "Lewis O'Brien",
            440 to "Andrew Omobamidele",
            441 to "Jonathan Panzo",
            442 to "Ibrahim Sangaré",
            443 to "Matz Sels",
            444 to "Harry toffolo",
            445 to "Matt Turner",
            446 to "Hwang Ui-jo",
            447 to "Chris Wood",
            448 to "Joe Worrall",
            449 to "Ryan Yates",
            573 to "Nikola Milenković",
            596 to "João Pedro Ferreira Silva",
            450 to "Carlos Alcaraz Durán",
            451 to "Samuel Amo-Ameyaw",
            452 to "Joe Aribo",
            453 to "Adam Armstrong",
            454 to "Gavin Bazunu",
            455 to "Jan Bednarek",
            456 to "Armel Bella-Kotchap",
            457 to "James Bree",
            458 to "Shea Charles",
            459 to "Samuel Edozie",
            460 to "Ronnie Edwards",
            461 to "Taylor Harwood-Bellis",
            462 to "Kamaldeen Sulemana",
            463 to "Adam Lallana",
            464 to "Juan Larios López",
            465 to "Mateusz Lis",
            466 to "Joe Lumley",
            467 to "Ryan Manning",
            468 to "Sékou Mara",
            469 to "Alex McCarthy",
            470 to "Paul Onuachu",
            471 to "Will Smallbone",
            472 to "Jack Stephens",
            473 to "Ross Stewart",
            474 to "Sugawara Yukinari",
            475 to "Charlie Taylor",
            476 to "Kyle Walker-Peters",
            477 to "Nathan Wood-Gordon",
            518 to "Flynn Downes",
            584 to "Ben Brereton Díaz",
            608 to "Tyler Dibling",
            82 to "Dominic Solanke-Mitchell",
            478 to "Ashley Phillips",
            479 to "Brandon Austin",
            480 to "Rodrigo Bentancur",
            481 to "Lucas Bergvall",
            482 to "Yves Bissouma",
            483 to "Bryan Gil Salvatierra",
            484 to "Ben Davies",
            485 to "Alfie Devine",
            486 to "Radu Drăgușin",
            487 to "Emerson Leite de Souza Junior",
            488 to "Fraser Forster",
            489 to "Archie Gray",
            490 to "Pierre-Emile Højbjerg",
            491 to "Brennan Johnson",
            492 to "Dejan Kulusevski",
            493 to "Giovani Lo Celso",
            494 to "James Maddison",
            495 to "Pedro Porro",
            496 to "Sergio Reguilón",
            497 to "Richarlison de Andrade",
            498 to "Cristian Romero",
            499 to "Pape Matar Sarr",
            500 to "Dane Scarlett",
            501 to "Oliver Skipp",
            502 to "Manor Solomon",
            503 to "Son Heung-min",
            504 to "Djed Spence",
            505 to "Destiny Udogie",
            506 to "Micky van de Ven",
            507 to "Alejo Véliz",
            508 to "Guglielmo Vicario",
            509 to "Timo Werner",
            510 to "Alfie Whiteman",
            609 to "Will Lankshear",
            610 to "Mikey Moore",
            612 to "Wilson Odobert",
            388 to "Aaron Wan-Bissaka",
            511 to "Edson Álvarez Velázquez",
            512 to "Michail Antonio",
            513 to "Alphonse Areola",
            514 to "Jarrod Bowen",
            515 to "Maxwel Cornet",
            516 to "Vladimír Coufal",
            517 to "Aaron Cresswell",
            519 to "George Earthy",
            520 to "Emerson Palmieri dos Santos",
            521 to "Łukasz Fabiański",
            522 to "Wes Foderingham",
            523 to "Danny Ings",
            524 to "Max Kilman",
            525 to "Mohammed Kudus",
            526 to "Luis Guilherme Lira dos Santos",
            527 to "Lucas tolentino Coelho de Lima",
            528 to "Konstantinos Mavropanos",
            529 to "Nayef Aguerd",
            530 to "tomáš Souček",
            531 to "James Ward-Prowse",
            532 to "Kurt Zouma",
            576 to "Andy Irving",
            587 to "Crysencio Summerville",
            588 to "Guido Rodríguez",
            589 to "Niclas Füllkrug",
            591 to "Jean-Clair todibo",
            533 to "Rayan Aït-Nouri",
            534 to "Boubacar Traoré",
            535 to "Jean-Ricner Bellegarde",
            536 to "Daniel Bentley",
            537 to "Francisco Jorge tomás Oliveira",
            538 to "Tawanda Chirewa",
            539 to "Leon Chiwome",
            540 to "Luke Cundle",
            541 to "Matheus Santos Carneiro Da Cunha",
            542 to "Craig Dawson",
            543 to "Matt Doherty",
            544 to "tommy Doyle",
            545 to "Fábio Silva",
            546 to "Nathan Fraser",
            547 to "Enso González",
            548 to "Gonçalo Manuel Ganchinho Guedes",
            549 to "Hugo Bueno López",
            550 to "Hwang Hee-chan",
            551 to "Joe Hodge",
            552 to "Ki-Jana Hoever",
            553 to "João Victor Gomes da Silva",
            554 to "José Malheiro de Sá",
            555 to "Saša Kalajdžić",
            556 to "tom King",
            557 to "Mario Lemina",
            558 to "Yerson Mosquera",
            559 to "Nélson Cabral Semedo",
            561 to "Pedro Cardoso de Lima",
            562 to "Daniel Castelo Podence",
            563 to "Rodrigo Martins Gomes",
            564 to "Santiago Bueno",
            565 to "Pablo Sarabia",
            566 to "Jørgen Strand Larsen",
            567 to "toti António Gomes"

        )
    }
}